// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClearData():Promise<void>;

export function ExportCSV():Promise<string>;

export function ExportJSON():Promise<string>;

export function GetDashboardStats():Promise<models.DashboardStats>;

export function GetScanData():Promise<models.ScanData>;

export function ImportFile():Promise<models.ScanData>;

export function ImportFilePath(arg1:string):Promise<models.ScanData>;
