// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearData() {
  return window['go']['main']['App']['ClearData']();
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function ExportJSON() {
  return window['go']['main']['App']['ExportJSON']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetScanData() {
  return window['go']['main']['App']['GetScanData']();
}

export function ImportFile() {
  return window['go']['main']['App']['ImportFile']();
}

export function ImportFilePath(arg1) {
  return window['go']['main']['App']['ImportFilePath'](arg1);
}
